# Generated by Django 4.1.3 on 2022-12-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PremisSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, help_text='Settings value', max_length=200)),
                ('key', models.CharField(help_text='Settings key (must be unique - case insensitive', max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Premis Setting',
                'verbose_name_plural': 'Premis Settings',
            },
        ),
    ]
