# Generated by Django 4.1.3 on 2022-12-19 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import premis.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machinecategory',
            options={'verbose_name': 'Machine Category', 'verbose_name_plural': 'Machine Categories'},
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Machine name', max_length=100, validators=[premis.validators.validate_machine_name], verbose_name='Name')),
                ('IPN', models.CharField(blank=True, help_text='Internal Part Number', max_length=30, null=True, verbose_name='IPN')),
                ('description', models.CharField(blank=True, help_text='Description (optional)', max_length=250, verbose_name='Description')),
                ('active', models.BooleanField(default=True, help_text='Is this machine active?', verbose_name='Active')),
                ('creation_date', models.DateField(auto_now_add=True, null=True, verbose_name='Creation Date')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('category', mptt.fields.TreeForeignKey(blank=True, help_text='Machine category', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='machines', to='machine.machinecategory', verbose_name='Category')),
                ('creation_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machine_created', to=settings.AUTH_USER_MODEL, verbose_name='Creation User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
