# Generated by Django 4.1.3 on 2022-12-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name', max_length=30, verbose_name='Name')),
                ('value_in_day', models.SmallIntegerField(help_text='Value in day', verbose_name='Value in day')),
            ],
            options={
                'verbose_name': 'Period',
                'verbose_name_plural': 'Periods',
                'ordering': ['value_in_day'],
            },
        ),
        migrations.AddConstraint(
            model_name='period',
            constraint=models.UniqueConstraint(fields=('name', 'value_in_day'), name='unique_name_email_pair'),
        ),
    ]
