# Generated by Django 4.1.3 on 2022-12-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='period',
            name='unique_name_email_pair',
        ),
        migrations.AddConstraint(
            model_name='period',
            constraint=models.UniqueConstraint(fields=('name', 'value_in_day'), name='unique_name_value_in_day_pair'),
        ),
    ]
