# Generated by Django 4.1.3 on 2022-12-20 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import premis.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0002_remove_period_unique_name_email_pair_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name', max_length=100, validators=[premis.validators.validate_check_item_name], verbose_name='Name')),
                ('description', models.CharField(blank=True, help_text='Description (optional)', max_length=250, verbose_name='Description')),
                ('creation_date', models.DateField(auto_now_add=True, null=True, verbose_name='Creation Date')),
            ],
            options={
                'verbose_name': 'Check Item',
                'verbose_name_plural': 'Check Items',
            },
        ),
        migrations.RemoveConstraint(
            model_name='period',
            name='unique_name_value_in_day_pair',
        ),
        migrations.AddConstraint(
            model_name='period',
            constraint=models.UniqueConstraint(fields=('name', 'value_in_day'), name='unique_name_email_pair'),
        ),
        migrations.AddField(
            model_name='checkitem',
            name='creation_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_item_created', to=settings.AUTH_USER_MODEL, verbose_name='Creation User'),
        ),
        migrations.AddField(
            model_name='checkitem',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='check_items', to='task.period'),
        ),
    ]
