# Generated by Django 4.1.4 on 2022-12-20 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('machine', '0003_remove_machine_level_remove_machine_lft_and_more'),
        ('task', '0004_remove_period_unique_name_email_pair_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, help_text='Description (optional)', max_length=250, verbose_name='Description')),
                ('creation_date', models.DateField(auto_now_add=True, null=True, verbose_name='Creation Date')),
                ('creation_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_created', to=settings.AUTH_USER_MODEL, verbose_name='Creation User')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='task.checkitem', verbose_name='Item')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='machine.machine', verbose_name='Machine')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('machine', 'item'), name='unique_machine_task_pair'),
        ),
    ]
