# Generated by Django 4.1.4 on 2022-12-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_task_task_unique_machine_task_pair'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='task',
            name='unique_machine_task_pair',
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('machine', 'item'), name='unique_machine_item_pair'),
        ),
    ]
