# Generated by Django 4.0.8 on 2023-04-13 03:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0006_remove_task_unique_machine_task_pair_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(verbose_name='Remarks')),
                ('creation_date', models.DateField(auto_now_add=True, null=True, verbose_name='Submitted on')),
                ('creation_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record_created', to=settings.AUTH_USER_MODEL, verbose_name='Submitted by')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskrecord', to='task.task', verbose_name='Task')),
            ],
            options={
                'verbose_name': 'record',
                'verbose_name_plural': 'records',
            },
        ),
    ]
